//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst.DB_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FristEntities : DbContext
    {
        public DB_FristEntities()
            : base("name=DB_FristEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        public DbSet<T_COURES_SUBJECT_MAP> T_COURES_SUBJECT_MAP { get; set; }
        public DbSet<T_COURSES> T_COURSES { get; set; }
        public DbSet<T_SUBJECT> T_SUBJECT { get; set; }
        public DbSet<T_USERTYPE> T_USERTYPE { get; set; }
        
    }
}
