//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COURSES
    {
        public T_COURSES()
        {
            this.T_COURES_SUBJECT_MAP = new HashSet<T_COURES_SUBJECT_MAP>();
        }
    
        public int ID { get; set; }
        public string Course_Name { get; set; }
        public string Descriptions { get; set; }
    
        public virtual ICollection<T_COURES_SUBJECT_MAP> T_COURES_SUBJECT_MAP { get; set; }
    }
}
