//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COURES_SUBJECT_MAP
    {
        public int ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual T_COURSES T_COURSES { get; set; }
        public virtual T_SUBJECT T_SUBJECT { get; set; }
    }
}
