//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> UserType { get; set; }
    
        public virtual T_USERTYPE T_USERTYPE { get; set; }
    }
}
